# API Configuration
api:
  bybit:
    testnet: true
    api_key: "YOUR_BYBIT_API_KEY"
    api_secret: "YOUR_BYBIT_API_SECRET"
  
  telegram:
    bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
    chat_id: "YOUR_TELEGRAM_CHAT_ID"

# Trading Pairs (Top 20 by market cap)
trading_pairs:
  - "BTC/USDT"
  - "ETH/USDT"
  - "BNB/USDT"
  - "SOL/USDT"
  - "XRP/USDT"
  - "ADA/USDT"
  - "AVAX/USDT"
  - "DOT/USDT"
  - "MATIC/USDT"
  - "LINK/USDT"
  - "UNI/USDT"
  - "ATOM/USDT"
  - "FIL/USDT"
  - "LTC/USDT"
  - "BCH/USDT"
  - "NEAR/USDT"
  - "ALGO/USDT"
  - "VET/USDT"
  - "ICP/USDT"
  - "HBAR/USDT"

# Timeframes for analysis
timeframes:
  - "5m"
  - "15m"
  - "1h"
  - "4h"
  - "1d"

# Model Configuration
models:
  ensemble_weights:
    lstm: 0.25
    cnn: 0.20
    transformer: 0.25
    xgboost: 0.15
    sentiment: 0.15
  
  confidence_threshold: 75.0
  
  lstm:
    sequence_length: 100
    hidden_units: [256, 128, 64]
    dropout: 0.2
    epochs: 100
    batch_size: 32
  
  cnn:
    image_size: [64, 64]
    filters: [32, 64, 128]
    kernel_size: 3
    epochs: 50
    batch_size: 16
  
  transformer:
    context_length: 500
    num_heads: 8
    num_layers: 6
    d_model: 512
    epochs: 75
    batch_size: 8
  
  xgboost:
    n_estimators: 1000
    max_depth: 6
    learning_rate: 0.01
    subsample: 0.8
  
  sentiment:
    model_name: "nlptown/bert-base-multilingual-uncased-sentiment"
    max_length: 512

# Data Configuration
data:
  historical_days: 365
  update_interval: 60  # seconds
  cache_enabled: true
  cache_duration: 300  # seconds

# Logging
logging:
  level: "INFO"
  file: "logs/trading_bot.log"
  max_file_size: "10MB"
  backup_count: 5

# Database
database:
  path: "data/trading_signals.db"
  backup_enabled: true
  backup_interval: 3600  # seconds
